[package]
name = "meta"
version = "0.1.0"
authors = ["Alexey Shmalko <rasen.dubi@gmail.com>"]
edition = "2018"

[dependencies]
meta-store = { path = "./meta-store" }

[workspace]
members = [
    "meta-store",
    "meta-pretty",
    "meta-core",
]
